00:00:00.004939 main     VirtualBox COM Server 7.0.4 r154605 win.amd64 (Nov 16 2022 15:33:13) release log
00:00:00.004946 main     Log opened 2023-01-05T00:43:25.449088800Z
00:00:00.004948 main     Build Type: release
00:00:00.004967 main     OS Product: Windows 11
00:00:00.004969 main     OS Release: 10.0.22000
00:00:00.004970 main     OS Service Pack: 
00:00:00.032139 main     DMI Product Name: 82H8
00:00:00.044764 main     DMI Product Version: IdeaPad 3 15ITL6
00:00:00.044779 main     Firmware type: UEFI
00:00:00.045109 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.045131 main     Host RAM: 7991MB (7.8GB) total, 1517MB available
00:00:00.045135 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.045136 main     Process ID: 109244
00:00:00.045136 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.109028          VirtualBox: object creation starts
00:00:00.109193          Home directory: 'C:\Users\harsh\.VirtualBox'
00:00:00.109282          Installed Drivers:
00:00:00.112697            C:\Windows\system32\DRIVERS\VBoxSup.sys (Version: 7.0.4.4605)
00:00:00.113000            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 7.0.4.4605)
00:00:00.113265            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 7.0.4.4605)
00:00:00.113551            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 7.0.4.4605)
00:00:00.113868          Loading settings file "C:\Users\harsh\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.114922          usbLibGetDevices: Starting USB device enumeration
00:00:00.153900          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:00:00.153961          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:00:00.155576          usbLibGetDevices: Found 2 USB devices, 0 captured
00:00:00.155625          USB: Unknown USB device detected (idVendor: 0x0bda, idProduct: 0xc123)
00:00:00.155664          USB: Unknown USB device detected (idVendor: 0x174f, idProduct: 0x2459)
00:00:00.187959          HostDnsMonitor: initializing
00:00:00.192783          HostDnsMonitor: updating information
00:00:00.192805          HostDnsMonitor: old information
00:00:00.192805            no server entries
00:00:00.192806            no domain set
00:00:00.192806            no search string entries
00:00:00.192806          HostDnsMonitor: new information
00:00:00.192806            server 1: 192.168.1.1
00:00:00.192807            domain: home
00:00:00.192807            no search string entries
00:00:00.241884          VD: VDInit finished with VINF_SUCCESS
00:00:00.243166          Loading settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:00:00.243988          VirtualBox: object created
00:00:00.634557          Launched VM: 1715628304 pid: 85360 (0x14d70) frontend: GUI/Qt name: ISE_14.7_VIRTUAL_MACHINE
00:00:09.371812          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={70401eef-c8e9-466b-9660-45cb3e9979e4} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:00:27.695264          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={SessionMachine} aText={The machine is not mutable or saved (state is Restoring)}, preserve=false aResultDetail=0
00:00:28.580954          NetworkServiceRunning: started 'VBoxNetDHCP.exe', pid 000187b0
00:00:30.402756          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Property 'CRYPT/KeyId' does not exist}, preserve=false aResultDetail=0
00:00:30.405397          Added USB filter (ID=1, type=4) for device 03FD:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:00:30.405787          Added USB filter (ID=2, type=4) for device 0403:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:00:30.405811          Added USB filter (ID=3, type=4) for device 1443:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:00:39.425802          Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:00:39.439407          Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
00:01:25.100801 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:01:25.136431 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:01:25.137095 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:01:25.138779 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
00:03:26.050451 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:03:26.079095 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:03:26.079290 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:03:26.079850 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
00:10:33.613402          Removed USB filter ID=1
00:10:33.614116          Removed USB filter ID=2
00:10:33.614137          Removed USB filter ID=3
00:10:33.635178          Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:10:33.641965          Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
00:10:33.863671 SaveState Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:10:33.869874 SaveState Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
00:10:40.656147 main     VirtualBox: object deletion starts
00:10:40.656204 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\14.7_VM-disk001.vmdk' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
00:10:40.658848 main     NetworkServiceRunning: killing VBoxNetDHCP.exe, pid 000187b0...
00:10:40.664777 main     HostDnsMonitor: shutting down ...
00:10:40.664911 main     HostDnsMonitor: shut down
00:10:40.668263 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={7682d5eb-f00e-44f1-8ca2-99d08b1cd607} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:10:40.669043 main     VirtualBox: object deleted
