00:00:00.003391 main     VirtualBox COM Server 7.0.4 r154605 win.amd64 (Nov 16 2022 15:33:13) release log
00:00:00.003393 main     Log opened 2023-01-03T18:35:31.812556300Z
00:00:00.003393 main     Build Type: release
00:00:00.003398 main     OS Product: Windows 11
00:00:00.003399 main     OS Release: 10.0.22000
00:00:00.003399 main     OS Service Pack: 
00:00:00.033168 main     DMI Product Name: 82H8
00:00:00.048202 main     DMI Product Version: IdeaPad 3 15ITL6
00:00:00.048211 main     Firmware type: UEFI
00:00:00.048467 main     Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:00.048483 main     Host RAM: 7991MB (7.8GB) total, 989MB available
00:00:00.048487 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.048487 main     Process ID: 107536
00:00:00.048488 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.236047          VirtualBox: object creation starts
00:00:00.236447          Home directory: 'C:\Users\harsh\.VirtualBox'
00:00:00.237868          Installed Drivers:
00:00:00.250213            C:\Windows\system32\DRIVERS\VBoxSup.sys (Version: 7.0.4.4605)
00:00:00.251201            C:\Windows\system32\DRIVERS\VBoxUSBMon.sys (Version: 7.0.4.4605)
00:00:00.252264            C:\Windows\system32\DRIVERS\VBoxNetAdp6.sys (Version: 7.0.4.4605)
00:00:00.253009            C:\Windows\system32\DRIVERS\VBoxNetLwf.sys (Version: 7.0.4.4605)
00:00:00.253748          Loading settings file "C:\Users\harsh\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.255820          usbLibGetDevices: Starting USB device enumeration
00:00:00.344031          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:00:00.344085          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:00:00.345830          usbLibGetDevices: Found 2 USB devices, 0 captured
00:00:00.345874          USB: Unknown USB device detected (idVendor: 0x0bda, idProduct: 0xc123)
00:00:00.345907          USB: Unknown USB device detected (idVendor: 0x174f, idProduct: 0x2459)
00:00:00.405042          HostDnsMonitor: initializing
00:00:00.415023          HostDnsMonitor: updating information
00:00:00.415069          HostDnsMonitor: old information
00:00:00.415069            no server entries
00:00:00.415070            no domain set
00:00:00.415071            no search string entries
00:00:00.415071          HostDnsMonitor: new information
00:00:00.415071            server 1: 192.168.1.1
00:00:00.415072            domain: home
00:00:00.415073            no search string entries
00:00:00.497962          VD: VDInit finished with VINF_SUCCESS
00:00:00.500026          Loading settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:00:00.501403          VirtualBox: object created
00:00:00.692021          Launched VM: 1839804928 pid: 109580 (0x1ac0c) frontend: GUI/Qt name: ISE_14.7_VIRTUAL_MACHINE
00:00:13.018772          ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={An unexpected process (PID=0x0001A830) has tried to lock the machine 'ISE_14.7_VIRTUAL_MACHINE', while only the process started by LaunchVMProcess (PID=0x0001AC0C) is allowed}, preserve=false aResultDetail=0
00:00:14.221058          ERROR [COM]: aRC=VBOX_E_INVALID_OBJECT_STATE (0x80bb0007) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={The machine 'ISE_14.7_VIRTUAL_MACHINE' is already locked by a session (or being locked or unlocked)}, preserve=false aResultDetail=0
00:00:21.285689          ERROR [COM]: aRC=VBOX_E_VM_ERROR (0x80bb0003) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={MachineWrap} aText={Failed to assign the machine to the remote session (RPC_S_CALL_FAILED/0x800706be)}, preserve=false aResultDetail=0
00:00:43.839641          Launched VM: 1804341728 pid: 110824 (0x1b0e8) frontend: GUI/Qt name: ISE_14.7_VIRTUAL_MACHINE
00:00:51.746272          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={70401eef-c8e9-466b-9660-45cb3e9979e4} aComponent={ExtPackManagerWrap} aText={No extension pack by the name 'Oracle VM VirtualBox Extension Pack' was found}, preserve=false aResultDetail=0
00:00:58.767461          ERROR [COM]: aRC=VBOX_E_INVALID_VM_STATE (0x80bb0002) aIID={300763af-5d6b-46e6-aa96-273eac15538a} aComponent={SessionMachine} aText={The machine is not mutable or saved (state is Restoring)}, preserve=false aResultDetail=0
00:00:59.356433          NetworkServiceRunning: started 'VBoxNetDHCP.exe', pid 000183c4
00:01:01.632400          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Property 'CRYPT/KeyId' does not exist}, preserve=false aResultDetail=0
00:01:01.634333          Added USB filter (ID=1, type=4) for device 03FD:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:01:01.634381          Added USB filter (ID=2, type=4) for device 0403:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:01:01.634400          Added USB filter (ID=3, type=4) for device 1443:FFFFFFFF rev FFFFFFFF, c/s/p FFFFFFFF/FFFFFFFF/FFFFFFFF, Manufacturer=`<null>' Product=`<null>' Serial=`<null>'
00:01:13.626444          Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:01:13.634202          Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
00:04:07.507670 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:04:07.537752 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:04:07.537929 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:04:07.538822 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
00:40:58.375670 EventHandler Event: forcefully unregistering passive event listener 000002296db0b2a0 due to excessive queue size
00:46:52.440479 USBPROXY usbLibGetDevices: Starting USB device enumeration
00:46:52.471045 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
00:46:52.471226 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
00:46:52.475464 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
00:55:27.714789          Removed USB filter ID=1
00:55:27.715451          Removed USB filter ID=2
00:55:27.715487          Removed USB filter ID=3
00:55:27.762785          Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:55:27.768797          Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
00:55:28.004724 SaveState Saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox" with version "1.19-windows"
00:55:28.012109 SaveState Finished saving settings file "C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\ISE_14.7_VIRTUAL_MACHINE.vbox"
01:22:16.532902 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:22:16.610180 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
01:22:16.610308 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:22:16.611757 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:23:44.466985 USBPROXY usbLibGetDevices: Starting USB device enumeration
01:23:44.496917 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 5
01:23:44.497071 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&3881863d&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 10
01:23:44.497440 USBPROXY usbLibGetDevices: Found 2 USB devices, 0 captured
01:30:21.433925 main     VirtualBox: object deletion starts
01:30:21.434478 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\harsh\VirtualBox VMs\ISE_14.7_VIRTUAL_MACHINE\14.7_VM-disk001.vmdk' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
01:30:21.438062 main     NetworkServiceRunning: killing VBoxNetDHCP.exe, pid 000183c4...
01:30:21.444276 main     HostDnsMonitor: shutting down ...
01:30:21.444377 main     HostDnsMonitor: shut down
01:30:21.446724 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={7682d5eb-f00e-44f1-8ca2-99d08b1cd607} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
01:30:21.447655 main     VirtualBox: object deleted
